Viewloggeduser
Maciek246/blogport-front pull request #17
Opened 2019-01-07 15:02 UTC by arcziri

Added show buttons for user when user is logged and for guest when user isn't logged:
-Added new folder into structure project it is context we will use into include component CurrentUserProvider. Now is component included in file App.js
-Edit template JSX in index.js with component MainNavbar

2019-01-07 15:19 UTC, Maciek246 requested changes

2019-01-07 15:19 UTC, Maciek246 commented on src/App.js
> +            <CurrentUserProvider>
Why do you use a Context API? We are using a Redux. I don't understand why we should use this when all functions from Context which are necessary in our app we have in Redux

2019-01-08 18:00 UTC, Maciek246 approved these changes
Looks fine, I thought about button for create new blog too but ok, it wasn't part of this task and I don't have form too. Approved.

2019-01-08 18:38 UTC, kateotto approved these changes

2019-01-08 18:38 UTC, merged