[AddPostPanel] Validation add post panel
Maciek246/blogport-front pull request #23
Opened 2019-01-10 23:22 UTC by arcziri

-added validation into form to create new post

2019-01-11 15:36 UTC, Maciek246 commented
In commits: [branch_name]. Dont write inside random names.

2019-01-11 15:46 UTC, Maciek246 requested changes

2019-01-11 15:46 UTC, Maciek246 commented on src/App.js
> +            <Route exact path="/:addblog/slug" component={BlogLovWeb} />
Why? Its nonsense. We don't have variable 'addblog'. Nowhere. In this form routing our app is broken.

2019-01-11 15:46 UTC, Maciek246 commented on src/App.js
> +            <Route exact path="/:addblog" component={AddBlog} />
Again. ":" char is for 'variable' in url. 'addblog' is static route. Remove ":".

2019-01-11 15:46 UTC, Maciek246 commented on src/components/AddBlogPanel/index.js
> +        this.submitaddBlogForm = this.submitaddBlogForm.bind(this);
In ES6 exists arrow function which gives a possibility avoid a bind(this). But it's not a necessary.

2019-01-11 15:46 UTC, Maciek246 commented on src/components/AddBlogPanel/index.js
> +    submitaddBlogForm(e) {
Use camelcase

2019-01-11 15:46 UTC, Maciek246 commented on src/components/MainNavbar/index.js
> +                <Link to="/:addblog"><button className="button--main-navbar blue">Utwórz nowy blog</button></Link>
Ditto: 'addblog' is static route not route with a variable.

2019-01-11 15:46 UTC, Maciek246 commented on src/components/AddPostPanel/index.js
> +        this.submitaddPostForm = this.submitaddPostForm.bind(this);
Ditto: ES6 syntax

2019-01-11 15:46 UTC, Maciek246 commented on src/components/AddPostPanel/index.js
> +    submitaddPostForm(e) {
Ditto: camelcase

2019-01-12 14:24 UTC, Maciek246 requested changes

2019-01-12 14:24 UTC, Maciek246 commented on src/App.js
> +            <Route exact path="/:addblog/slug" component={BlogLovWeb} />
This isn't fixed.

2019-01-12 14:24 UTC, Maciek246 commented on src/App.js
> +            <Route exact path="/:addblog" component={AddBlog} />
Ditto: In this case, you sold remove only ":" from this line.

2019-01-12 14:38 UTC, arcziri commented on src/App.js
> +            <Route exact path="/:addblog/slug" component={BlogLovWeb} />
I wrote to you that when it change this is another mistake and you wrote to me that you will change it

2019-01-12 14:39 UTC, arcziri commented on src/App.js
> +            <Route exact path="/:addblog" component={AddBlog} />
I wrote to you that when it change this is another mistake and you wrote to me that you will change it

2019-01-12 14:42 UTC, Maciek246 commented on src/App.js
> +            <Route exact path="/:addblog/slug" component={BlogLovWeb} />
Yes, but you should comment these lines and write a comment with info about it.

2019-01-12 15:28 UTC, Maciek246 approved these changes

2019-01-12 15:56 UTC, merged